version: '3.8'

services:
  minecraft:
    build: .
    container_name: minecraft_server
    ports:
      - "25565:25565"    # Port Minecraft
      - "24454:24454/udp" # Port Proximity Chat (Simple Voice Chat)
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      MEMORY: "4G"
      ONLINE_MODE: "false"
      ENABLE_RCON: "true"
    restart: unless-stopped
